[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.install]
cmds = [
  "cd backend",
  "npm ci --only=production"
]

[phases.build]
cmds = [
  "cd backend",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"